### ISSUE TITLE
Why are these unique?

### ISSUE THREAD

**Issue by jetaggart** [walkrick/rantly#3]
https://github.com/walkrick/rantly/blob/master/app/models/user.rb#L8-L10

Why can't a user have the same first_name, last_name or bio? Many people have the same names.

**Comment by walkrick** [comment]
Removed the uniqueness factor for first& last name and the bio

**Comment by jetaggart** [comment]
I don't see a change.

**Comment by walkrick** [comment]
Sorry, I fixed the problem and then didn't push to github.  Should be good now.
